### ISSUE TITLE
ncnn  load multimodel on gpu failed

### ISSUE THREAD

**Issue by cqray1990** [Tencent/ncnn#1862]
HI:
when i load multimodel on gpu ,examples i have three models , pnet,fnet,onet and i adopt the method as follows
ncnn:create_gpu_instance()
pnet.opt.use_vulkan_compute=true;
fnet.opt.use_vulkan_compute=true;
onet.opt.use_vulkan_compute=true;===========>lstm

but i raise :
out of blob allocator
out of staging allocator

and i comment 
//fnet.opt.use_vulkan_compute=true;
//onet.opt.use_vulkan_compute=true;
pnet can run success but the rest networks can not.

i hope your reply!
thank you

**Comment by cqray1990** [comment]
i try to put the https://github.com/ouyanghuiyu/chineseocr_lite project on gpu

**Comment by nihui** [comment]
fixed

**Comment by cqray1990** [comment]
@nihui   i am sorry to tell  it ‘s not solved，“out of blob allocator
out of staging allocator”  error is gone，but  the result is Null，i cann’t get the correct reconition results？is something wrong？

**Comment by nihui** [comment]
> @nihui i am sorry to tell it ‘s not solved，“out of blob allocator
> out of staging allocator” error is gone，but the result is Null，i cann’t get the correct reconition results？is something wrong？

已QQ群沟通解决 www
