### ISSUE TITLE
Segmentation fault when benchmarking a model

### ISSUE THREAD

**Issue by AbhinavMehrotra** [Tencent/ncnn#1991]
I am trying to benchmark a model [[located here](https://github.com/LicheeX/MTCNN-NCNN/blob/master/models/det1.param)] using the benchmark profiler provided [[here](https://github.com/Tencent/ncnn/blob/master/benchmark/benchncnn.cpp)]. In the benchncnn.cpp file I have changed the `ex.extract("output", out);` to `ex.extract("prob1", out);` to match the output name of the model. 

However, the run fails with an error saying just `Segmentation fault`. Can anyone help with this?

**Comment by nihui** [comment]
If you are using the ncnn code from git master branch, I suggest checking out the recent tag 20200727, or update master branch and try again, as I just fixed a potential segfault crash on some new arm64 devices.

**Comment by AbhinavMehrotra** [comment]
Thanks for the swift reply! I have updated the local branch to `54e79a6`, but the issue is still there. 
I am new to NCNN so struggling to debug the issue.

**Comment by nihui** [comment]
Is the input shape matching what the model needs ?
```
benchmark("yolov4-tiny", ncnn::Mat(416, 416, 3), opt); // the second parameter
```

**Comment by AbhinavMehrotra** [comment]
Yes. Here is the model, for example:

`7767517
12 13
Input            data             0 1 data 0=3 1=12 2=12
Convolution      conv1            1 1 data conv1 0=10 1=3 2=1 3=1 4=0 5=1 6=270
PReLU            PReLU1           1 1 conv1 conv1_PReLU1 0=10
Pooling          pool1            1 1 conv1_PReLU1 pool1 0=0 1=2 2=2 3=0 4=0
Convolution      conv2            1 1 pool1 conv2 0=16 1=3 2=1 3=1 4=0 5=1 6=1440
PReLU            PReLU2           1 1 conv2 conv2_PReLU2 0=16
Convolution      conv3            1 1 conv2_PReLU2 conv3 0=32 1=3 2=1 3=1 4=0 5=1 6=4608
PReLU            PReLU3           1 1 conv3 conv3_PReLU3 0=32
Split            splitncnn_0      1 2 conv3_PReLU3 conv3_PReLU3_splitncnn_0 conv3_PReLU3_splitncnn_1
Convolution      conv4-1          1 1 conv3_PReLU3_splitncnn_1 conv4-1 0=2 1=1 2=1 3=1 4=0 5=1 6=64
Convolution      conv4-2          1 1 conv3_PReLU3_splitncnn_0 conv4-2 0=4 1=1 2=1 3=1 4=0 5=1 6=128
Softmax          prob1            1 1 conv4-1 prob1 0=0`

`benchmark("det1", ncnn::Mat(3, 12, 12), opt); `

Also, I have modified the `ex.extract("output", out);` to `ex.extract("prob1", out);`

**Comment by nihui** [comment]
The shape ```ncnn::Mat(3, 12, 12)``` is probably wrong.
Try ```ncnn::Mat(12, 12, 3)```

**Comment by AbhinavMehrotra** [comment]
That's works! thanks!

But the original model has `Input            data             0 1 data 0=3 1=12 2=12`, so why do we need to change it to `12,12,3`? Is there any assumption?

**Comment by nihui** [comment]
The Input layer parameter is wrong, it should be 0=12 1=12 2=3.
